# R44: 共享 OKX 品种列表，platform 和 historyd 共用
OKX_DEFAULT_INSTRUMENTS = [
    "BTC-USDT", "ETH-USDT", "SOL-USDT", "BNB-USDT", "XRP-USDT", "DOGE-USDT",
    "ADA-USDT", "AVAX-USDT", "DOT-USDT", "LINK-USDT", "MATIC-USDT", "UNI-USDT",
    "BTC-USDT-SWAP", "ETH-USDT-SWAP", "SOL-USDT-SWAP", "BNB-USDT-SWAP",
    "XRP-USDT-SWAP", "DOGE-USDT-SWAP", "ADA-USDT-SWAP", "AVAX-USDT-SWAP",
    "ATOM-USDT", "NEAR-USDT", "OP-USDT", "ARB-USDT", "APT-USDT",
    "LTC-USDT", "FIL-USDT", "ETC-USDT", "AAVE-USDT", "XAUT-USDT",
    "TRX-USDT", "SHIB-USDT", "SUI-USDT", "WIF-USDT", "PEPE-USDT",
    "ETH-BTC", "SOL-BTC",
]
